### ISSUE TITLE
[Feature Request] NBT Matching and Attributes

### ISSUE THREAD

**Issue by ambonmibable** [MEGATREX4/inventory-weight#5]
I've been trying to use this mod with TaCZ and KubeJS, and, while the mod is amazing, it doesn't have the best customization for complex modpack development (or I haven't been able to find the features).
 
Being able to apply weights to items based on what NBT they have would be great for TaCZ as that mod reuses the same items with differing NBT depending on gun, ammo, attachment, etc. (9mm Bullets are `tacz:ammo{AmmoId:"tacz:9mm"}`)
This might be more complicated for guns, as they change NBT frequently (firing mode, remaining ammo, attachments).

Additionally, being able to apply stat changes with attributes would be wonderful. I've been adding randomized stats to crafted items and being able to add additional pockets/max weight/weight multiplier when they're equipped is something that I'd love to have access to.

##### Requesting from 1.3.2, Forgefied mc1.20.1

**Comment by DevMC7** [comment]
hey! We sadly can't add NBT support for every mod due to the variety of NBT structures there can be in many different mods. However, you can customize item weights under `config/inventory_weights_items.json`. Support for configuring NBT in that config file will probably be added in the future, so your first problem will be solved.

Currently, the mod modifies the `ENERIC_MOVEMENT_SPEED`, `GENERIC_ATTACK_SPEED`, `GENERIC_ATTACK_DAMAGE` to apply weight penalties (you can find their UUIDs [here](https://github.com/MEGATREX4/inventory-weight/blob/main/src/main/java/com/megatrex4/effects/OverloadEffect.java)). We might also add more datapack options in the future

also, please note that we won't be adding direct forge support; the mod is developed in fabric but works on forge with connector

thanks for your feedback :)

**Comment by DevMC7** [comment]
I've started working on it

Here is the current config structure that will handle it:

`
{
  "bundleWeight": { /* you can name this whatever you want */
    "item": "minecraft:bundle", /* the item to check for nbt */
    "weightWhenNbt": {
      "item": /* the nbt key to check*/ {
        "value": "minecraft:glass", /* if the nbt key's value is equal to this */
        "weight": 100 /* add this weight */
      }
    }
  }
}
`


So the structure for that mod would be

`
{
  "AmmoWeight": {
    "item": "tacz:ammo",
    "weightWhenNbt": {
      "AmmoId": {
        "value": "tacz9mm",
        "weight": 100
      }
    }
  }
}
`

**Comment by MEGATREX4** [comment]
Added in the next update
